pipeline {

    agent any  { dockerfile true }

    stages {
       stage('Test') {
           agent {
               docker {
                   image 'maven:3.8.6-openjdk-11-slim'
               }
           }
            steps {
                sh 'pytest -q'
            }
        }
        stage('Lint') {
            agent {
                docker {
                    image 'maven:3.8.6-openjdk-11-slim'
                }
            }
            steps {
                sh 'pip install -r requirements.txt flake8 mypy'
                sh 'make lint'
            }
        }
        // STAGES DE EJERCICIOS
        // practica 2.1
        stage('Info') {
            steps {
                echo "Job: ${env.JOB_NAME}"
                echo "Build: ${env.BUILD_NUMBER}"
                echo "Branch: ${env.BRANCH_NAME}"
            }
        }
        // final del bloque de stages
    }
}
