pipeline {

    agent any

    stages {

        // ejercicio 2.1
        stage('Info') {
            steps {
                echo "2.1 Info"
                echo "Job: ${env.JOB_NAME}"
                echo "Build: ${env.BUILD_NUMBER}"
                echo "Branch: ${env.BRANCH_NAME}"
            }
        }
        // ejercicio 2.2 + 2.3
        stage('CI - Lint') {
            steps {
                sh 'python --version'
                sh 'pip install -r requirements.txt'
                sh 'make lint'
            }
        }

        stage('CI - Test') {
            agent {
                docker {
                    image 'python:3.6-slim'
                }
            }
            steps {
                echo "2.2 Unit test"
                sh 'pytest -q'
            }
        }
        // final del bloque de stages
    }
}
